### ISSUE TITLE
ivy conflicts in consult-gh

### ISSUE THREAD

**Issue by fkgruber** [armindarvish/consult-gh#135]
**Describe the bug**
loading ivy stops consult-gh from working

**To Reproduce**
before loading ivy I can do 
```
consult-gh-issue-list 
openvax/isovar
```
but after loading
```
(use-package ivy)
(ivy-mode 1)
 ```
I no longer get the list of issues. I get matched required error.
<img width="763" alt="image" src="https://github.com/user-attachments/assets/1e22055e-7820-46d2-b22e-648413414f25">

**Important Information:**
 - OS: mac os
 - Version of Emacs : 29.1
 - Version of `gh` (run `gh --version` in a shell)
 ```
gh version 2.52.0 (2024-06-24)
https://github.com/cli/cli/releases/tag/v2.52.0
```
 - Version of `consult` 20240824.800
 - The installation method and the configuration you are using with your consult-gh.
 ```
(use-package consult-gh
  :straight (consult-gh :type git :host github :repo "armindarvish/consult-gh")
  :after consult

  :config
  ;;add your main GitHub account (replace "armindarvish" with your user or org)
  (add-to-list 'consult-gh-default-orgs-list "armindarvish")

  ;;use "gh org list" to get a list of all your organizations and adds them to default list
  (setq consult-gh-default-orgs-list (append consult-gh-default-orgs-list (remove "" (split-string (or (consult-gh--command-to-string "org" "list") "") "\n"))))

  ;; set the default folder for cloning repositories, By default Consult-GH will confirm this before cloning
  (setq consult-gh-default-clone-directory "~/gitRepos/"))
```

**Comment by armindarvish** [comment]
@fkgruber I just tested ivy with `consult-grep` and that does not work either.  This seems to be because of the incompatibility of upstream consult with ivy! (see this: https://github.com/minad/consult/issues/212). Basically, it seems that there is no support for consult-async with ivy and there is no plan for it because there are alternatives like vertico (that said I cannot claim I know much about that so maybe you should ask @minad if the plans have changed on that front). 

There is nothing we can do about this in consult-gh. Therefore, I am closing this now.
