### ISSUE TITLE
extract repository information from .git

### ISSUE THREAD

**Issue by fkgruber** [armindarvish/consult-gh#137]
Hi

with gh if I'm in a shell and I visit a repository and I type gh issue list I get the list of issues without having to specify the owner or repository name. I expected consult-gh to behave in the same way.

However, if I go to the repository in dired or magit and I do M-x consult-gh-issue-list it asks for owner and repository.

Why not figure out this information from the directory? What am I missing?

thanks
FKG

**Comment by armindarvish** [comment]
@fkgruber 

You can use M-n to access future history and if you are in a git repository, the first item suggested would be the repo in the current directory. 


> Why not figure out this information from the directory? What am I missing?
Because what happens if you are in the wrong directory. Forcing this based on the current directory (directory default in Emacs) is not a great idea because in buffers that are not visiting a file, the default directory can be ambiguous. Using future history, the current repo is one 'M-n' keypress away, and yet the user can pick any repo s(he) wishes.

Plus the fact that `consult-gh` is generally not designed around the idea of handling local repositories but rather finding/fetching ad-hoc information (like readme, issues, single files, ...) for one-of/temporary use from remote repositories on github without cloning them locally. Otherwise, for local repos, you can always use magit + forge, or other packages. In fact in my personal usage, I rarely want to see information about a local repo, but rather I need to search for issues/files, etc. in a relevant/related repo (like a dependency) that I do not keep a local copy of.
