### ISSUE TITLE
Why can't I see private repos?

### ISSUE THREAD

**Issue by agzam** [armindarvish/consult-gh#152]
This isn't an issue, at this point this is merely a question. I just joined a new team and I am failing to list the repos, enforced through SAML. I have my tokens configured and authorized. 

I don't remember this being a problem, I probably miss something, can you suggest an easy way to troubleshoot this?

**Comment by agzam** [comment]
Ah darn, I did it again. My apologies. I asked this question [before](https://github.com/armindarvish/consult-gh/issues/82). Sorry for being so obtuse and short-memoried.

**Comment by armindarvish** [comment]
@agzam Just FYI, since you mentioned joining a new team. I recently added support for multi-account login and switching between accounts as well. This has been supported by the gh client for a while, and I recently added support for it in consult-gh as well.

You can simply login with multiple accounts with gh auth login and then use `consult-gh-auth-switch` in emacs.
