### ISSUE TITLE
Extrapolate current repo 

### ISSUE THREAD

**Issue by agzam** [armindarvish/consult-gh#34]
I just installed the package and I have to say, this will definitely be one of the main tools I use every day. It's very nicely done. Thank you!

I noticed that `consult-gh-issue-list` doesn't recognize the repository it's looking at when executed from within a certain project, unless that repository has already been added to the list of repos (in which case, you still have to choose it from the list). I think it would be nice if the tool could extrapolate the repo for the current project.

In general, it seems that there are a few places where there is an opportunity to improve the "intelligence" of the package. For example, if I have the `consult-gh-preview` buffer open for a repository (after using `consult-gh-org`), then the next command, `consult-gh-repo-clone` prompt should automatically reuse the name of the repository.

**Comment by armindarvish** [comment]
I think, what you are asking would be nice. I thought about this before as well. gh itself can recognize a repo from working directory and do actions, but at the same time I use magit for most of those things anyway, and I figured this is not a high priority. I think it's relatively easy t incorporate what you are asking since all I am doing is making calls to gh in the shell anyway. But what I need to know is how the UI would be designed. When do I go by project, v.s. by searching online? How do we give users the flexibility to do both without adding too many extra features that are already out there in other packages? 

If you can think of some good way of improving the package while maintaining the simple and intuitive ui, I am open to implementing them.

**Comment by agzam** [comment]
I tried it with consult-gh-find-file and consult-gh-find-file and it works great. Thank you!

**Comment by armindarvish** [comment]
I actually ended up adding a third option, the string "suggest", for `consult-gh-prioritize-local-folder` so that instead of skipping the query it simply uses the local folder as the default value in the minibuffer. This is perhaps the closest to what is intuitively expected.

```emacs-lisp 
(setq consult-gh-prioritize-local-folder "suggest")
```

**Comment by agzam** [comment]
You probably want it to be rather a symbol than string, i.e., `(setq consult-gh-prioritize-local-folder 'suggest)`

**Comment by armindarvish** [comment]
Yeah that's probably better, let me fix that now.

**Comment by armindarvish** [comment]
@sethidden Good catch! It seems that I forgot to update update the code after changing to async approach to fully respect `consult-gh-prioritize-local-folder`. This is now fixed in main branch. 

For context, the reason I forgot to do this is because since switching to dynamically updated completion tables (using consult--async), the option of setting `consult-gh-prioritize-local-folder` to `'t` (or `'nil` for that matter) does not make a lot of practical sense because as you noted the current repo is accessible through "M-n" when you set it to `'suggest` and that is easy enough, so I never bothered to test the other options. 

I now fixed that so if people do this all the time and want to save themselves the "M-n" key press, they can use the `consult-gh-prioritize-local-folder` as intended.
