### ISSUE TITLE
Deleting orgs from ` consult-gh--known-orgs-list`

### ISSUE THREAD

**Issue by agzam** [armindarvish/consult-gh#37]
Currently, there's no quick and convenient way of deleting orgs from `consult-gh--known-orgs-list`, is there?

**Comment by armindarvish** [comment]
No, there is not, so right now `(setq consult-gh--known-orgs-list (delete "org" consult-gh--known-orgs-list))` is your best bet. It's very easy to add an interactive command with completing-read if you need, but do we really need one more interactive command just for this? I kind of like not having too many interactive commands. Or would you want an embark action for deleting orgs or repos from know lists? That would be out of the way but still available.

**Comment by agzam** [comment]
Embark-action is a way to do it, but I think, first, there has to be something done in order for Embark to understand what it is. Currently, an item in the consult-gh list treated as an ordinary string.

**Comment by armindarvish** [comment]
Yes, but that can easily be done. Currently 'consult-gh-orgs' is using completing-read to ask for name of orgs you are searching for but I can also use 'consult' instead and in that case I will have a new category that Embark recognizes.

**Comment by oantolin** [comment]
> It's very easy to add an interactive command with completing-read if you need, but do we really need one more interactive command just for this?

For what it's worth, the Embark "philosophy", if you want to call it that, is that yes, you should have interactive commands for anything you want to do. That way no-one is left out: non-Embark users can call those commands; and Embark users can choose to never call them directly, only as Embark actions.

If you write non-interactive functions for use as Embark actions, that's nice for Embark users, but is inconvenient for people that for some reason or other don't want to use Embark.

**Comment by armindarvish** [comment]
> > It's very easy to add an interactive command with completing-read if you need, but do we really need one more interactive command just for this?
> 
> For what it's worth, the Embark "philosophy", if you want to call it that, is that yes, you should have interactive commands for anything you want to do. That way no-one is left out: non-Embark users can call those commands; and Embark users can choose to never call them directly, only as Embark actions.
> 
> If you write non-interactive functions for use as Embark actions, that's nice for Embark users, but is inconvenient for people that for some reason or other don't want to use Embark.

@oantolin Since we are talking philosophy, let me share my thoughts on this 😆

I guess I agree with the general sentiment of allowing users to choose their way of doing things, at the same time that is a *general* philosophy, and may not be right for this context because allowing many different ways of doing the same thing can confuse the user. So, personally I think: 

- For a search and completion task (like anything with consult-), we need a clear entry point for the user. When I do `M-x consult-gh-` I don't want to see many completion possibilities because then it becomes confusing for the user where to start (e.g. shall I first search for repos and then browse the contents or shall I use find-file? Should I do `consult-gh-issue-list` or `consult-gh-search-issues`). Pretty much every time you have a search function, a clean general search (like the Google's homepage) is the way to go, rather than creating many paths with all sorts of options to achieve the same thing. For this reason, I would like to avoid too many interactive commands and keep them for the essentials. Everything else can be non-interactive, but still called through embark.

- Unlike many other packages, only a selected group of users will choose to browse the GitHub inside Emacs with consult-gh. The majority would probably still prefer the browser. I expect that this selected group can figure out how to add their own interactive commands if needed based on what is provided by default. This way, the user will add commands for what is essential in their workflow, rather than us trying to cater to every possible need we can imagine.

**Comment by armindarvish** [comment]
@argzam This is now addressed. I added embark actions for adding and removing orgs to known list and for repos to both known list and default list.

I ended up using `completing-read-multiple` and added categories per embark manual and it works. @oantolin, I asked @miand on consult repo about using completing-read-multiple, and he suggested the way to go is to use embark-select and embark-act-all, but that would then require binding keys in the minibuffer to those and also typing new entries won't work as it does with `completing-read-multiple` and `crm-separator`. Do you have any suggestions, or know examples for a better UI than using the crm-separator and `complting-read-multiple`?

**Comment by agzam** [comment]
Nice, thank you @armindarvish I have this now and it works beautifully: 

```emacs-lisp
(defun consult-gh-remove-org+ (x)
  (interactive)
  (setq consult-gh--known-orgs-list
        (cl-delete x consult-gh--known-orgs-list :test #'string=))
  (message "Deleted '%s' org from list of orgs." x))
  
(map! :map consult-gh-embark-orgs-actions-map
      "k" #'consult-gh-remove-org+)
```

**Comment by oantolin** [comment]
@armindarvish Sure, leaving some functions non-interactive to have fewer entry points is a valid design too. It's not typically what Emacs chooses, for example, consider file operations: they could only be available from dired buffers, but Emacs has a full set of standalone interactive commands (`copy-file`, `rename-file`, `delete-directory`, `delete-file`, `chmod`, `make-directory`) in addition to the dired commands. Does this clutter `M-x`? Maybe, but you're not supposed to worry about that (I currently have 4590 commands listed by `M-x` and I don't care!). For another example, consider package management: Emacs could choose to make those only available in the buffer you get from `list-packages`, but it doesn't, it additionally has a full set of standalone package management commands. All of these standalone file or package commands, I never call directly from `M-x`, I only ever call them as Embark actions, but I'm glad they're there for non-Embark users to bind to keys or whatever (I used to have a file-operations prefix keymap, before writing Embark).

But if you want fewer `consult-gh` commands and want to require Embark for convenient access to the non-interactive actions, that's perfectly fine too, it is definitely your choice. I feel a little weird here defending the interests of people who _don't like Embark!_.

And with regard to `completing-read-multiple`: it works fine with Embark. What minad must have meant is that _if you want_ Consult previews or other Consult niceties _and_ you also want the user to be able to select multiple candidates _and_ what you are going to do to each of the chosen candidates is the same thing, _then_ you can use `consult--read` to write the one-candidate-at-a-time version with previews or whatnot, and let users handle the multiple candidate case through Embark. There are plenty of ways with Embark: you can just run `embark-dwim` on each candidate you want, or you can narrow the candidate list until just the ones you want match and then use `embark-act-all`, or, you can use `embark-select` to selects some candidates and then use `embark-act-all`.

Basically, Embark will let you pretend that any command that uses `completing-read` is a command that uses `completing-read-multiple` but does the same thing to each chosen candidate. For example, when writing emails I very often need to attach several files, so I press `C-c C-a`, which runs `mml-attach-file`, just once and use Embark to run the default action on all the files I want to attach —instead of running `mml-attach-file` multiple times, once for each attachment.

If you don't need any Consult fanciness for a given command, then `completing-read-multiple` is fine. But if you wanted, say, Consult previews, since there is no `consult--read-multiple`, you need to decide how important the previews are vs how important the ability to choose several things is. And minad's point is that Embark can take care of the multiplicity aspect, so you don't really need `completing-read-multiple`. (Of course if you do something more complicated that doing exactly the same thing to each chosen candidate, then you really need `completing-read-multiple`).

**Comment by armindarvish** [comment]
@oantolin I think for now fewer interactive commands are better if not for anything else for purely selfish reasons because I have to maintain this and adding more interactive commands makes it hard. Once everything is a bit more stable, we can add all sorts of interactive commands, I guess.

With regard to completing-read-multiple, is there a way to have embark-act-all to use the list of selected items and run a command on them just once instead of looping? Let's say I want to clone multiple repos, I have a function to query the user for the target folder, but if the user selects multiple repos by using embark-select, I only want to do the query once rather than for every each repo. I already have this working with completing-read-multiple, but there are cases where I am using consult and I want to be able to do this.

**Comment by oantolin** [comment]
> With regard to completing-read-multiple, is there a way to have embark-act-all to use the list of selected items and run a command on them just once instead of looping?

Yes, those are called multitarget actions. They are non-interactive functions that take a single argument which is a list of targets. You have to register them in the `embark-multitarget-actions` list. For example, in the default configuration, `w` runs a multitarget action, which concatenates all targets and adds that concatenation as a single entry in the kill-ring.

**Comment by oantolin** [comment]
And about the commands vs non-interactive functions as actions, let me emphasize that I do think that your plan of having fewer interactive functions is also a perfectly valid design choice. It may not be what Emacs built-in packages tend to do, but it is what Helm and Ivy/Counsel do, for example.
