### ISSUE TITLE
Marginalia info

### ISSUE THREAD

**Issue by agzam** [armindarvish/consult-gh#38]
`consult-gh-orgs` and `consult-gh-search-repos` show some useful info, would be nice to add the list of languages used in the repo (e.g., so we could filter all elisp repos). Also, make sure that the annotations are nicely lined up, currently they are not aligned.

It looks like in order to retrieve that (and some additional) info, `gh` will have to work in json mode, e.g., `gh search repos SOME-REPO --json fullName,language`

**Comment by armindarvish** [comment]
Well, there are two different set of requirements you are referring to:

1- adding info to the marginalia is relatively easy, aligning it takes a bit more since some of those things are very dynamic and when we work with something as big as the entire github repository, there are two many edge cases to consider. So, I am not sure how much time I am willing to spend on aligning things.

2- AFAIK, filtering based on marginalia (e.g. narrow down candidates based on matches for what you type in the minibuffer) is not supported in the upstream `consult` and that is very much a built-in challenge with completing read. I think that has to be addressed in upstream packages (if possible) not in this one.

**Comment by agzam** [comment]
The first one, I'm not sure myself how to achieve, tbh.

For the second thing I also contemplated and scratched my head once. I ended up doing hackiest, stupidest thing that worked :). I took all the annotation text and concatenated to the main text but set the property to `invisible`. https://github.com/agzam/browser-hist.el/blob/main/browser-hist.el#L165

That tricks completing-read to be able to narrow not only based on the main string, but also annotations.

**Comment by armindarvish** [comment]
Ok, that sounds interesting. if I find some time I'll experiment with that.
 I am guessing that the hacky solution would not look as good because the completion matching highlight won't be happening in the marginalia, but it's definitely worth a try if we can narrow down based on anything in the marginalia. It opens up for a bunch of other improvements as well.

**Comment by oantolin** [comment]
Another way to narrow by annotation is to run `embark-collect` and then `consult-focus-lines` in the resulting buffer. It's a little awkward, but works.

**Comment by armindarvish** [comment]
@agzam, I recently updated the package and reimplemented everything to enable dynamic update with consult-sync. In the process, I ended up doing something similar to what you did. So now you can narrow down based on marginalia info too. I'm now closing this issue
