### ISSUE TITLE
How does narrowing work?

### ISSUE THREAD

**Issue by agzam** [armindarvish/consult-gh#47]
When running `consult-gh-default-repos`, if you press `consult-narrow-key` (it's configured to `<` for me), you can narrow down the list for a selected org.

But I noticed, because I have `consult-gh-default-orgs-list` with orgs that start with the same letter "a", it doesn't let me narrow for both orgs.

e.g., if you set `consult-gh-default-orgs-list` to be something like `("alpha" "adventure" "aadvark")`, running the above command won't let you narrow the repos to show what's only in "adventure" org, or in "aadvark" org.

And for `consult-gh-search-repos`, narrowing doesn't work at all

**Comment by armindarvish** [comment]
Yes, that is the case. The challenge with narrowing is to find the right conditionals. It's hard to create a narrowing function that generally applies and is at the same time useful. So, I figured that going by the initial letter is good enough with a "one key" selection. In the case where you have multiple orgs with the same initial letter, then narrowing to just the ones starting with "a" might be "good enough", especially because you can also search with minibuffer completion including regex completion! I use vertico-cycle to jump between groups too, so at the end I rarely need the narrowing. But, if you have any other ideas for how we can do better narrowing, let me know. 

For search-repos, I need to check why the narrowing is not working.

**Comment by armindarvish** [comment]
I am closing this issue now because I redesigned the whole package to enable consult-async and narrowing is not really needed anymore.
