### ISSUE TITLE
Visit github issue with forge without cloning entire repo

### ISSUE THREAD

**Issue by ParetoOptimalDev** [armindarvish/consult-gh#55]
This is supported as per https://github.com/magit/forge/issues/102, but it's not quite straight-forward or provided in a single function. It doesn't seem too difficult to add though given consult-gh will have the info to correctly call both `forge-add-repostiory` and if it supports it, providing the topic id from the consult-gh search.

**Comment by ParetoOptimalDev** [comment]
It looks like consult-gh-forge--issue-view would need modified somehow.

**Comment by ParetoOptimalDev** [comment]
> @ParetoOptimalDev Can you please elaborate? Currently, `consult-gh-forge--issue-view-action` does exactly what you are asking for. It does not clone the entire repo, and you can see the issues and interact with them as you would normally do in forge. This comment itself is being sent from forge right now!

When I tried using it on the nixpkgs repo it hung, but maybe it just took longer than I expected for the bare repo.

Will check again.

**Comment by armindarvish** [comment]
@ParetoOptimalDev Can you please share the name of the repo and the issue number you were trying to load?

Sometimes if there are a lot of comments and posts under an issue it can take some time to load it, which has nothing to do with `consult-gh`. This would also take a long time to load in forge without consult-gh unless you clone the repo and have everything stored in the local database. Even in the browser, loading everything would take a long time. When there are many comments and posts, the website loads a limited number of entries and you have to keep clicking on "Load more ..." To see them all which is even slower. For an example try looking at https://github.com/minad/consult/issues/6

This 917 comments, and the browser only loads about 50 of them! I can still open this in consult-gh using forge but it takes several seconds to load. If you do this often, then you need to increase the value of `consult-gh-forge-timeout-seconds`

There are of course ways to improve the behavior to load a limited number of entries, but if you are using forge to view the issues, that has to happen in forge (which probably does not make sense since forge uses local database anyway) and not in `consult-gh`!

**Comment by ParetoOptimalDev** [comment]
I just replicated using this issue:

https://github.com/NixOS/nixpkgs/issues/253198

I got to it by using `consult-gh-search-repo`, entering `nixos/nixpkgs`, searching `haskell`, and then hitting enter aka calling `consult-gh-forge--issue-view-action`.

I did notice that when using `consult-gh-list-issues` I don't seem to have this problem. Going to wait and see if `consult-gh-search-repo` ever completes and will look at the location forge clones to to see if it cloned the full repo to verify.

**Comment by ParetoOptimalDev** [comment]
Nevermind, I have an issue with forge. Perhaps my version of forge isn't updated for emacs 29:

```
Debugger entered--Lisp error: (args-out-of-range #<buffer *forge-issue-list: nixos/nixpkgs*> 0 1)
  forge--topic-by-forge-short-link-at-point(("#") forge-get-issue)
  forge--issue-by-forge-short-link-at-point()
  forge-topic-at-point()
  forge-current-topic()
  byte-code("\300 \211\203\17\0\301\1\302\"\262\1\202\24\0\303\304!\262\1C\207" [forge-current-topic eieio-oref id forge-read-topic "View topic"] 4)
  command-execute(forge-visit-topic)
```

**Comment by ParetoOptimalDev** [comment]
It also has a similar hang even after fully cloning the repo, but really leaning towards this being a forge or forge on emacs 29 issue.

**Comment by armindarvish** [comment]
@ParetoOptimalDev Yes, I just tested with that same issue (https://github.com/NixOS/nixpkgs/issues/253198) and it works just fine. Here is a screenshot for reference:
![consult-gh-forge](https://github.com/armindarvish/consult-gh/assets/18317557/fdcd4964-97f1-4de6-9f95-fa52b794cca2)

I am also on Emacs >29. There must be something with your forge setup that is causing this.I am closing this issue for now.

**Comment by ParetoOptimalDev** [comment]
I just verified using `forge-20230901.1233` by debugging this function consult-gh calls:

```

(cl-defmethod forge-get-repository ((url string) &optional remote demand)
  "Return the repository at URL."
  (if-let ((parts (forge--split-url url)))
      (forge-get-repository parts remote demand)
    (when (memq demand forge--signal-no-entry)
      (error "Cannot determine forge repository.  %s isn't a forge url" url))))
```

The value of `demand` is `full`. It seems like maybe your version of forge is defaulting to `nil` and mine is defaulting to `full` for `forge-get-repository`.

A fix that would likely work for me is:

```diff
(defun consult-gh-forge--add-topic (url topic)
  "Add a repository to the forge database and only
pull individual topics when the user invokes `forge-pull-topic'. see forge documentation for `forge-add-repository'."
  (cl-letf (((symbol-function #'magit-toplevel)
             (lambda () (consult-gh--make-tempdir (string-join (cdr (forge--split-url url)) "/")))
             ))
    (let ((created (consult-gh-forge--add-repository url))
          (repo (forge-get-repository url)))
      (while (not repo)
        (sit-for 0.0001)
-        (setq repo (forge-get-repository url)))
+        (setq repo (forge-get-repository url nil nil)))
      (consult-gh-forge--pull-topic url topic)
      created
      )))
```

**Comment by ParetoOptimalDev** [comment]
After deleting the repo from forge and recreating it I can no longer reproduce this issue.

**Comment by ParetoOptimalDev** [comment]
This issue was resolved by doing `forge-reset-database`.

**Comment by ParetoOptimalDev** [comment]
Nevermind... I know the problem!

It only does a sparse clone the first time. The next time you call `forge-get-repository` after the first invocation created the repo in forges database it seems the second call clones the rest of it.
