### ISSUE TITLE
How to use gh-list and pr-list commands?

### ISSUE THREAD

**Issue by agzam** [armindarvish/consult-gh#93]
Since the async flow feature change I can't seem to be able to use `consult-gh-pr-list` anymore. I just can't figure out the simple use case where I need to find a PR by its number or description. 

I would run the command normally, it usually picks up the repo, if I'm running it while in the directory. It still prompts saying "Enter repo name", even though it clearly is expecting the PR parameters. But typing anything just throws "Could not resolve the repository... bla-bla". The only way to make it work is to explicitly type the search parameters after `--`, so it requires whole a lot more typing: `myorg/myrepo --search "is:closed 1842"` - ~if you don't explicitly state that you're looking within closed PRs it won't find it~ *(turns out this can be improved using vars, mentioned further)*.

It's pretty similar for the issues list. 

What's the recommendation for searching for PRs and Issues? Because out of the box, the commands don't feel very intuitive.

**Comment by armindarvish** [comment]
@agzam Are you saying that you don't see closed PRs? or you don't see anything?

Here are some tips/suggestions for you:

1- If you are inside a git repo directory, and you want to see pr list, you can do:
 a. `M-x consult-gh-pr-list`
 b. use `M-n` to get autocompletion for the repo in the current directory 
 (when `consult-gh-prioritize-local-folder` is set to `'suggest`, you can use `M-n` to get to current directory, otherwise if you set it to `t`, it should autocomplete to current directory without any key press but this is true only after #86 was merged so you may need to update!)
 c. Wait for the dynamic completion to get a list of issues. 
 
 If the probelm is that you are not seeinf closed PRs, then you have to 2 options:
 - use additional arguments such as "-- -s all" "-- -s closed", etc.
 - set the variable `consult-gh-prs-state-to-show` to "all" (or "merged" "closed", ...) to globally change the setting. You would still be able to override this by typing "-- -s open",... in the minibuffer input.
 
 2- If you are looking for PRs in another repo, you can use `C-u M-x consult-gh-pr-list`, in which case you will be asked to search for a repo (so you don't need to be accurate with the Owner/Repo input) and then that is used to autocomplete the input in `consult-gh-pr-list`). The rest is the same.
 
 The exact same approach should also work for `consult-gh-issue-list` (but you need to set `consult-gh-issues-state-to-show` for this one)
 
![Screen Recording 2023-11-13 at 2 17 00 PM](https://github.com/armindarvish/consult-gh/assets/18317557/ec477573-7497-4e78-86e7-06c408d054d7)

**Comment by agzam** [comment]
This is what I'm talking about:

![consult-gh](https://github.com/armindarvish/consult-gh/assets/1091022/8b222dd5-a9ae-4a0f-bcde-79f62d7ebe05)

I'd run `consult-gh-pr-list` or `consult-gh-issue-list`, it picks up the repo (or not depending on the settings), then it shows a list of things. Why can't I immediately start typing up text of numbers?

**Comment by agzam** [comment]
I kind of "improved" it for myself, making it possible to start typing text and numbers right away, with this:

```emacs-lisp
(defadvice! consult-gh-issue-list-a (orig-fn &optional initial noaction)
    :around #'consult-gh-issue-list
    :around #'consult-gh-pr-list
    (if initial
        (fn initial noaction)
      (let ((repo (consult-gh--get-repo-from-directory)))
        (funcall
         orig-fn
         (format "%s -- -S " repo)))))
```

*Apologies for the Doom macro, it's basically adding advice to both functions in one shot.*

For some reason it initially complains `unknown argument "30"; please quote all values that have spaces`, or in general, when there's nothing after `-S`, I see that message, but that's just tiny irritation at this point.

**Comment by agzam** [comment]
Holy cow... I get it now. It works if I append `#` right after the repo name. I swear, when I tried before that didn't work. I probably had older version or something. OMG, I'm so dumb. Please consider appending it by default. Closing this now. Sorry for wasting your time with my nonsense.

**Comment by armindarvish** [comment]
The "#" is specific to consult--async. Look at `consult-async-split-styles-alist` and `consult-grep` docs for more details on how to use it. I played around with automatically appending it, but I ended up deciding it's better not to do that because if you are searching for a sentence which includes spaces, then having "#" would block searches because essentially everything after the second "#" character is used for narrow-down from the completion table in minibuffer  and not for original search (like searching description of issues, ...). I feel like it's not too much of a hassle to add # when you want to switch to narrow down.

Note that if you want to force the async search to run with <3 characters you cna also insert "#" at the end. For example with `M-c consult-gh-search-repos`, I have to enter `#mu#` to see the results for mu otherwise the async completion does not run with just 2 caharcters.

I need to find some time to improve the documentation for all these interesting async features, but haven't had time yet.
